### ISSUE TITLE
Changing and reading the bom contents error

### ISSUE THREAD

**Issue by hamdidamar** [Autodesk-Forge/forge-configurator-inventor#408]
I found fault around [here ](https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/master/AppBundles/ExportBOMPlugin/ExportBOMAutomation.cs#L169 ) and [here ](https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/master/AppBundles/ExportDrawingAsPdfPlugin/Automation.cs#L51). Does not appear when compiling via visual studio, but detected as an error on vs code. The second problem can be solved simply by adding tostring at the end.  But i don't know how to solve the first problem
![image](https://user-images.githubusercontent.com/39102004/116985544-4f194600-acd5-11eb-8919-64a0ef5ea62e.png)
![image](https://user-images.githubusercontent.com/39102004/116985587-5f312580-acd5-11eb-8605-f48989129dbe.png)

Also, although I change the columns and compile the project, the incoming data does not change.

**Comment by hradilm** [comment]
Hello. Projects you are referencing above are Windows .NET Framework projects and therefore need to be compiled by Visual Studio, not VS Code. Those projects are Design Automation AppBudles, which are running on the Autodesk servers not your machine, so if you want to make there changes you need to upload them to DA afterwards. This can be either done manually, or automatically by running the server with the argument `bundles=true`.

**Comment by hamdidamar** [comment]
I am compiling from visual studio already. and I run the project from there. After the compilation, it works successfully on 13 projects. But errors appear where I point. And although I changed the code and compiled it, there is no change on the boom list.
I simply want to do, for example, I'll add the total quantity column. I write this
 `new Shared.Column { Label = "Material" },
   new Shared.Column { Label = "Total Quantity" }` 
[here ](https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/master/AppBundles/ExportBOMPlugin/ExportBOMAutomation.cs#L141)and add the property inside the [object](https://github.com/Autodesk-Forge/forge-configurator-inventor/blob/master/AppBundles/ExportBOMPlugin/ExportBOMAutomation.cs#L181).Like `material.Value,
                    row.TotalQuantity` then I compile and run the project. But there is no change in the boom data and the new column does not appear.

![image](https://user-images.githubusercontent.com/39102004/116994722-c1902300-ace1-11eb-903f-e4b347c43ec9.png)

as you can see in the picture when i print the boom data to console, there is no change
![image](https://user-images.githubusercontent.com/39102004/116995017-319ea900-ace2-11eb-821b-2a6be09a110c.png)

**Comment by hradilm** [comment]
Hello.

Let me elaborate on my earlier post in regards to your finding, that changes you make in the AppBundles has no effect. This project consist of two independent parts:
1. Most of the content of the WebApplication folder can run on your local machine, you can debug it there and any change you make there is visible in runtime right after you compile it and run it
2. Sources in the AppBundles directory are on the other hand compiled to dlls (we call them AppBundles), which does not run on your machine. Since Design Automation is a Cloud service allowing customers to run their code (AppBundles) on the Autodesk machines on the internet, those DLLs needs to be deliver there. That can be accomplished by the Design Automation API, which is in this case already employed in our WebApplication server. So, once you compile the AppBundles using Visual Studio, you need to ask the WebApplication code to publish your changed dlls on the Autodesk server. And that can be done by running the web server using this command `dotnet run bundles=true'.

Regards, Michal
