### ISSUE TITLE
if I change something I cannot publish

### ISSUE THREAD

**Issue by Gena-developer** [Autodesk-Forge/forge-configurator-inventor#483]
Hi, I have an issue, if I change something from folder components,  I cannot publish. I have this. Can help me somebody?

![Screenshot 2023-06-30 144049](https://github.com/Autodesk-Forge/forge-configurator-inventor/assets/114415779/2ea2bfbf-c14d-4a21-8ba2-76e06eeeec50)

**Comment by mivasi** [comment]
It seems like there is something wrong with your javascript build. Can you send here the whole build log?

**Comment by Gena-developer** [comment]
Sure it is here
[log.txt](https://github.com/Autodesk-Forge/forge-configurator-inventor/files/11923217/log.txt)

**Comment by mivasi** [comment]
It seems like you changed src\components\toolbar.js
And he is complaining you no longer use these imports:
  Line 34:3:   'NavAction' is defined but never used  no-unused-vars
  Line 35:3:   'Separator' is defined but never used  no-unused-vars
  Line 40:10:  'Service24' is defined but never used  no-unused-vars

It should be enough to remove them, since they are not used.

You can try to show your version after changes, so I can make sure if it can be anything else.

**Comment by Gena-developer** [comment]
Thanks I will check it

**Comment by Gena-developer** [comment]
unfortunately it didn't help, which version are you talking about?

**Comment by Gena-developer** [comment]
I updated visual studio and everything started working, thank you for your help.

**Comment by Gena-developer** [comment]
Unfortunately, the error has returned and I do not know how to fix it, if you have an idea, please send me

**Comment by mivasi** [comment]
It is because you CreditCost variable is not used. Build fails in case of violating coding guideline policy. @Gena-developer

**Comment by Gena-developer** [comment]
All good, thank your help.
